# Generated by Django 5.1.7 on 2025-03-31 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Whois",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="HelloUser", max_length=100, null=True
                    ),
                ),
                (
                    "passcode",
                    models.CharField(
                        blank=True, default="secure123", max_length=100, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, default="unknown", max_length=100, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        blank=True, default="zero", max_length=100, null=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "whois",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myst.whois"
                    ),
                ),
            ],
        ),
    ]
