# Generated by Django 5.1.7 on 2025-03-31 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myst", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="whois",
        ),
    ]
