# Generated by Django 5.1.7 on 2025-04-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myst", "0003_note_user_note_whois"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
