# Generated by Django 5.1.7 on 2025-04-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myst", "0004_alter_note_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
