# Generated by Django 5.1.7 on 2025-04-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myst", "0005_alter_note_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="user",
        ),
        migrations.AddField(
            model_name="note",
            name="username",
            field=models.CharField(
                blank=True, default="nouser", max_length=100, null=True
            ),
        ),
    ]
