# Generated by Django 5.1.7 on 2025-04-02 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myst", "0006_remove_note_user_note_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="reply_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="myst.note",
            ),
        ),
    ]
