# Generated by Django 5.1.7 on 2025-04-02 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myst", "0007_note_reply_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="reply_id",
        ),
        migrations.AddField(
            model_name="note",
            name="reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="myst.note",
            ),
        ),
    ]
