# Generated by Django 5.1.7 on 2025-04-04 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myst", "0008_remove_note_reply_id_note_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="isSeen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="note",
            name="seen_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
