# Generated by Django 5.1.7 on 2025-04-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Aarumi", "0002_rename_reply_to_aarumi_aarumi_reply"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aarumi",
            old_name="Aarumi_reply",
            new_name="aarumi_reply",
        ),
    ]
