# Generated by Django 5.1.7 on 2025-04-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aarumi", "0003_rename_aarumi_reply_aarumi_aarumi_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="aarumi",
            name="is_received",
            field=models.BooleanField(default=False),
        ),
    ]
